### ISSUE TITLE
Dev Issue: Clicking 'Mutal Aid Map' redirects to reach4help.org not localhost

### ISSUE THREAD

**Issue by jensren** [reach4help/reach4help#1347]

**Comment by shayantist** [comment]
Hey @jensren , thanks for the issue! Would you be able to provide a description to elaborate on what the issue is and what the expected behavior should be?

**Comment by jensren** [comment]
Sure @schowdhury8. Running the site in localhost and clicking the 'Mutual Aid Map' button results in being redirected to map.reach4help.org instead of localhost. I've attached a screenshot showing the URL after clicking the map button.
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/41408654/121100862-afb20c00-c7c8-11eb-93f9-32c1021b774b.png">
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/41408654/121100892-c0628200-c7c8-11eb-99f4-e2f7353eb9c5.png">

**Comment by shayantist** [comment]
That's expected, actually. The [site](https://github.com/reach4help/reach4help/tree/development/site) and [map](https://github.com/reach4help/reach4help/tree/development/map) are two separate React projects so you wouldn't be able to access either via localhost. We decided to make them separate since different teams were working on each project, so while there are some similar elements, the codebases are quite different.

**Comment by jensren** [comment]
Ah I see, thank you for letting me know!
