### ISSUE TITLE
Figure out if can track clicks on specific events

### ISSUE THREAD

**Issue by ethanstrominger** [reach4help/reach4help#1352]

**Comment by shayantist** [comment]
@ethanstrominger Firebase has a great built-in way to do this: https://github.com/reach4help/reach4help/issues/1329

**Comment by disdyakis** [comment]
Algolia has Click and Conversion Analytics that require some extra configuration (the implementation of which will mainly depend on if we'll be using the[ InstantSearch for React library](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react/))

Based on [this article](https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-and-conversion-analytics/in-depth/capturing-user-behavior-as-events/#conversion-1), I think we'll want the following events to start out with:
- Result Clicked (from result list) [click]
- Pin Clicked (from map) [click]
- Link Followed (from result detail) [conversion]

There are two different types of event tracking methods, one where you send the queryId that generated the result (e.g. clickedObjectIdsAfterSearch) and one where you don't (e.g. clickedObjectIds). In order to get a `queryId` in the search response, you have to enable the `clickAnalytics` parameter in the call like so: `index.search('', { attributesToRetrieve: null, clickAnalytics: true });`

One approach would be to send `queryId` along with events associated with the search and search list (so Result Clicked and Pin Clicked if the pin that was clicked was in the most recent set of search results), and then not sending `queryId` when a user is just manually browsing via the map. I think that will make the analytics provided more useful in the long run.
