### ISSUE TITLE
Design the ER diagram for the MVP

### ISSUE THREAD

**Issue by wr46** [reach4help/reach4help#150]
There is a initial diagram on ~~[dbdiagram.io](https://dbdiagram.io/d/5e70e38f4495b02c3b885ca5)~~ we need to design the ER diagram for our MVP.

V2 ERD: [dbdiagram.io](https://dbdiagram.io/d/5e7bc93a4495b02c3b88c6c8)

Action:
- Add the exported PostgreSQL script into ./api/documentation/database/*.sql repo
    - #159 includes a copy of V2 at the moment
- Use [dbdiagram.io](https://dbdiagram.io/home) online tool for the ER design so we can import it after

**Comment by rgharris** [comment]
A few thoughts after reviewing the [workflow](https://www.lucidchart.com/documents/edit/e7b62422-f9ff-4f99-8558-ad99b56e219c/0_0?shared=true) and the schema diagram. Take these with a grain of salt as I am not very familiar with the details of the plans outside of these documents.

1. For `address` in #159 (@sabind), `address2` and `address3` could probably be nullable
2. `request.status` probably should be an enum or a FK? A FK to a status table would be more future proof
3. #127 is considering Auth0 for authentication, if that is the case then `authentication` won't be necessary
4. Will an external service like Twilio Verify be used to verify phone numbers or will that flow happen in the backend? If the latter, will need support for that in the schema.
5. Should `requester_id` and `volunter_id` be named `requester_user_id` and `volunteer_user_id` for clarity?
6. Usually I defer to using `timestamp with time zone` rather than `timestamp`. Here is [one explanation of that](https://justatheory.com/2012/04/postgres-use-timestamptz/)
7. Is the team/organization structure finalized yet? That seems like a pretty specific setup that might be subject to change during/after the MVP. That might could be simplified for now.

Are the following going to be part of the MVP? If so, they may require additional schema. Of course, designing this iteratively and deferring till later rather than upfront is definitely a good approach.

1. Messaging - if so using with something like Twilio Programmable Chat or building internally? 
2. Priority of cases
3. Ratings
4. Tracking offer rejections

**Comment by puzzledbytheweb** [comment]
> Are the following going to be part of the MVP? If so, they may require additional schema. Of course, designing this iteratively and deferring till later rather than upfront is definitely a good approach.
> 
> Messaging - if so using with something like Twilio Programmable Chat or building internally?
> Priority of cases
> Ratings
> Tracking offer rejections

1 - This is a feature we have discarded from the MVP but probably will happen somewhere along the way - Probably not needed at this stage and makes more sense in terms of architecture to, when we implement the messaging feature to be like a module/plugin with its own database relations.

2 - This is something quite important but it creates some problems that we are not able to solve yet for the MVP (how do we prioritize the cases? Age of PIN? Does thee PIN have illnesses?). Nonetheless, I think that this field/table can definitely exist at this stage, even if that feature is still not implemented.

3 - We've discussed this and, for the MVP, this will be an existent internal feature (so definitely a field/table for that), even though the user will not be able to see the ratings on the first version.

4 - This is a good point. If the volunteer rejects the request he's been assigned to - though for the MVP he will be self-assigned - we should keep track of this. Also, we might also keep track of requests that are canceled by PINs after having a volunteer assigned to.

About the overall schemas, they look good to me.

Thanks!

**Comment by wr46** [comment]
This was the first basic suggestion, it is very likely that it will get a major refactor.
The aim was to raise all of these issues in order to make a strong ER.
 Great feedback I'll add a schema into the repo so we can improve it, and add your suggestions into it.
I just have some doubts related to the table 'authentication'.
We will use Facebook login for now, and without the table, manage the authentication between client, server and idP will be a little bit tricky and many security issues.
How would you do it?

Keep the good work!

**Comment by sabind** [comment]
> For address in #159 (@sabind), address2 and address3 could probably be nullable

Addressed in the PR. That was definitely a typo :D

**Comment by sabind** [comment]
> request.status probably should be an enum or a FK? A FK to a status table would be more future proof @rgharris 

Using an enum (FK with Table) in the DB makes the data harder to read. Using the ORM to protect those values is easier to digest when investigating the DB or writing scripts.

**Comment by sabind** [comment]
>Should requester_id and volunter_id be named requester_user_id and volunteer_user_id for  clarity? @rgharris 

> Usually I defer to using timestamp with time zone rather than timestamp. Here is one explanation of that @rgharris 

Excellent points. Will update the PR

**Comment by sabind** [comment]
[Updated ERD](https://dbdiagram.io/d/5e7bc93a4495b02c3b88c6c8) with some additional considerations mentioned here

**Comment by sabind** [comment]
@s0 It might be worth it for us to use what we learned building the map out to provide feedback on the "Address, Contact, Organization" entities.

I realize now for example some orgs don't have addresses as they are entirely decentralized and only have a somewhat random lat + long.

**Comment by sabind** [comment]
@wr46 I've merged my PR and completed the following:

- added a `dbdigram.io.txt` file so we can continue the ERD over time
- added a `project-reach-4-help.sql` export from dbdiagram.io for documentation purposes.

**Comment by s0** [comment]
Little late to the party here, sorry about that, but I have a bunch of comments:

1. Organizations will [not be part of the MVP](https://github.com/reach4help/info#mvp-workflow). So it probably makes sense to leave them out of the initial schema. (Though i understand we may start wanting to get data in here for the map, which is a different matter, if we're doing that, i have additional thoughts below).
2. `service_type` should definitely be a table rather than an enum, we don't want to hard-code the types of services that people can request in the schema, we need a little bit more flexibility than that I would say. We probably also want to start off with a smaller set of types of services that are "request-able". If we want to use this data directly in the map then too, we probably need to have a flag to enable it in the app, something like:
   
   ```
   Table "service_type" {
     "id" BIGINT [pk, not null, increment]
     "label" VARCHAR [not null]
     "requestable" BOOLEAN [not null]
   }
   ```
   Beyond this, we'll probably want to have translations available for these services later on, not sure the best way to do this, perhaps referencing the id in the UI strings, or providing a `l10n_string` rather than a `label`.
3. There's no reference to `service_type` from `request`.
4. I think right from the start, we need to have some kind of log for requests, in particular to mark status changes, but also any particular action. Having a timeline of events is important for the MVP, something like this:

   ```
   Table "request_event" {
     "id" BIGINT [pk, not null, increment]
     "request_id" BIGINT  [not null]
     "timestamp" timestamp [not null]
     // set if the log message was due to a user action
     "user_triggering_action" BIGINT
     // set if logging a status change
     "new_status" request_status
     "message" text [not null]
   }
   
   Ref:"request_event"."request_id" < "request"."id"
   
   Ref:"request_event"."user_triggering_action" < "user"."id"
   
   Ref:"request_event"."new_status" < "user"."id"
   ```
   Perhaps it makes sense to combine this somehow into `comment`, we want to display messages alongside status changes within a single view in the UI, and at a high level they could be considered the same kind of thing?
5. I don't feel like the model of request status and `volunteer_user_id` is sufficient for modeling our needs here:
  * It should be possible for multiple offers of help to be in-flight at the same time
  * CAV's shouldn't be able to self-assign and then prevent any offers from other cavs (if they don't supply an offer)
  * it should be possible for a CAV to fail an accepted offer (e.g. pharmacy is out of required meds), and then release that for someone else to pick up.
    So i was thinking something a bit more like this:

    ```
    Enum "request_status" {
      "open"
      "completed"
      "canceled"
    }

    Enum "cav_assignment_status" {
      "pending_cav_acceptance"
      "cav_accepted"
      "offer_given"
      "offer_rejected"
      "in_progress"
      "completed"
      "failed"
    }

    Table "cav_assignment" {
      "request_id" BIGINT [not null]
      "cav" BIGINT [not null]
      "status" cav_assignment_status [not null]
    }

    Ref:"cav_assignment"."request_id" < "request"."id"
    Ref:"cav_assignment"."cav" < "user"."id"
    ```
6. It shouldn't be compulsory for users to have an address (i.e. volunteers).
7. we need a table for information about a PIN, stuff like their DOB, any health conditions etc... and a request should be with respect to them. There can then be a reference from a user to an entry in this table to allow us to determine if a user has done the on-boarding questionnaire.
8. Why do we need a username, requiring people to set a username is unnecessary if we're having other authentication mechanisms.

Beyond MVP:

* Once we do have organization information, I think that "teams" and "organizations" should be modeled in the same, way. And something is a "team" if it is an "organization with a parent". As it currently stands, they're not too different in the data model, and I foresee some situations where for example, one unit of an org registers as an organization, and then later their parent organization registers, and then suddenly you have 2 organizations in the datamodel, and no way of incorporating the existing org into the new org :)
