### ISSUE TITLE
Access Control List

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#204]
Create a document detailing who has access to the various systems, and who are the main points of contact etc...

cc @mdeous 

Any objection to making this kind of document public? I think it's best to.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/204)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mdeous** [comment]
@s0 No objection at all, I'm a big fan of doing things in the open. 

As not everyone has access to every system, I think this should be a collaborative effort from all team leads. I'll start drafting a spreadsheet in our security folder on GDrive and will share it with the rest of the team.

**Comment by s0** [comment]
@mdeous i was thinking it would be better as a markdown file in the info repo perhaps?

**Comment by TheRealAlexV** [comment]
Since we're also on the subject of access control... if we're going to put together an access entitlements matrix (access.md), it wouldn't be a bad idea to kill 2 birds with one stone and implement a role based access control policy and change management system.

The access.md doc can be our "Central source of truth", with all access changes needing to go through a git approval process before being merged and made effective.  This would put us in a good spot for compliance frameworks such as ISO and SOC.
