### ISSUE TITLE
Register as NGO / NPO

### ISSUE THREAD

**Issue by s0** [reach4help/reach4help#21]
See #20 

This will give us lots of benefits, in addition to easier fundraising.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/21)

*This information is updated automatically. To modify it, please use ZenHub.*

**Blocking:**

* **[BLOCKING: [#393](https://github.com/reach4help/reach4help/issues/393)]** [BLOCKED BY: [#21](https://github.com/reach4help/reach4help/issues/21)] [[@s0](https://github.com/s0), [@schowdhury8](https://github.com/schowdhury8), [@puzzledbytheweb](https://github.com/puzzledbytheweb)] [#21 - Get Bank Account](https://github.com/reach4help/reach4help/issues/392)
* ~~[#21 - Apply for SANTA CASA CHALLENGE](https://github.com/reach4help/reach4help/issues/394)~~
* [BLOCKED BY: [#21](https://github.com/reach4help/reach4help/issues/21)] [[@s0](https://github.com/s0)] [#21 - Register a Google for Nonprofits account](https://github.com/reach4help/reach4help/issues/20)
* [BLOCKED BY: [#21](https://github.com/reach4help/reach4help/issues/21)] [#21 - Setup Okta for SSO](https://github.com/reach4help/reach4help/issues/397)

**Comment by s0** [comment]
Looks like there may be some useful info here: https://charitysetup.org.uk/#download-checklist

**Comment by puzzledbytheweb** [comment]
I've contacted https://helpfulengineering.slack.com/archives/CUVPGT54J regarding this issue. Will contact a friend via WhatsApp that has experience setting up and accelerating social projects.

**Comment by puzzledbytheweb** [comment]
#legal-consulting Slack channel response https://helpfulengineering.slack.com/archives/CUVPGT54J/p1584794185004400

**Comment by puzzledbytheweb** [comment]
I've contacted my friend in WhatsApp, she pointed me towards https://tech4covid19.org/ and I'm waiting for a response by one of their leaders

**Comment by puzzledbytheweb** [comment]
So, I've spoken with one of the leads in Tech4Covid  and I've onboarded their slack channel.
I've explained our project and also that we have our connection with Helpful Engineers and he answered there was no problem in that and that their project would work as a pool of talent. If our project is chosen to be part of the endorsed projects by the Tech4Covid leadership we'll have access to their internal meeting (with their other projects).
Also, they appear to be quite skilled in Marketing/PR as they've caused som ripples around here, as managing to speak with the President.
I would like you to tell me what you need for your teams so that I can leverage their talent pool and maybe find the people we're lacking (namely a User Testing / QA lead?).

**Comment by schowdhury8** [comment]
Would it be feasible to alternatively register as a non-profit (NPO)? I could check up on filing for the US federal 501(c)(3) nonprofit status.

**Comment by TheRealAlexV** [comment]
Hi everyone. I can ask Stephen https://www.linkedin.com/in/stephen-scapelliti/ who is one of the co-directors of the Progressive Coders Network (a 501c4 in the usa with 501c3 in process) about advising us on the 501c3 application in the United States.  It's probably better to schedule a meet/zoom call for this.

**Comment by puzzledbytheweb** [comment]
Thanks! I would appreciate it very much.
