### ISSUE TITLE
Discuss about web-client hosting because of Netlify performance

### ISSUE THREAD

**Issue by puzzledbytheweb** [reach4help/reach4help#474]
### As mentioned on the MVP Standup - 27/04/2020:
Netlify doesn't have the stellar performance they advertise unless we upgrade to the Enterprise CDN plan which is expensive.

@sabind  suggested that we should discuss other alternatives such as Firebase, Google CDN or Cloudflare. 

Because Netlify has the amazing "deploy preview" feature on pull requests we also mentioned we could use Netlify solely for that purpose while using a more performant environment for the production deployment.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/474)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mdeous-datadog** [comment]
My call would be to keep netlify as the dev environment, and move staging and prod to Firebase as we're already using the product for other stuff. I don't think we should have yet one more different provider though.

My 2cts.

**Comment by mdeous** [comment]
My call would be to keep netlify as the dev environment, and move staging and prod to Firebase as we're already using the product for other stuff. I don't think we should have yet one more different provider though.

My 2cts.

**Comment by sabind** [comment]
+1 Firebase is actually the Google CDN by default.

**Comment by avaninosos** [comment]
We're allready using firebase and we have GCP partially funded. I think firebase and really anything GCP related at this point should be the primary preference when implementing new services. A totally free option could also be Github pages as well. 

FYI; Firebase hosting will ALWAYS be cheaper than going the plain old gcp bucket, cdn, LB setup.

**Comment by ashwinkjoseph** [comment]
I agree, firebase hosting already provides the CDN set up for us and we would be billed along with the rest of the GCP Project. so we could make use of GCP Credits if we get any.

But another point is that Netlify could have better performance than Firebase Hosting when we use their CDNs but the difference isn't a lot.

I was initially told by @jpmarques66 that we had some credits on Netlify if we could make use of those credits to get the CDN, then Netlify itself could be a better option, otherwise, I think the best choice could be Firebase Hosting itself

**Comment by sabind** [comment]
I'd only recommend firebase due to the ease of deployment (dev, staging, prod) and configuration using [reserved urls](https://firebase.google.com/docs/hosting/reserved-urls).

I think using netlify for PR testing is critical though and keeping it would be very helpful. Can we come to a consensus here? I'd like to configure the environments and deployments sooner that later so we can start end to end testing :)

**Comment by schowdhury8** [comment]
Closing as we settled for Firebase hosting in the end :)
