### ISSUE TITLE
[BUG] Map - Zooming makes portions of map disappear 

### ISSUE THREAD

**Issue by CorporateInvesther** [reach4help/reach4help#631]
**Describe the bug**
Zooming in and out of the map in both MAP and SATELLITE view makes sections of the map disappear. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an account, and land of the map screen
2. Zoom in and out of the map in both MAP and SATELLITE views
3. Notice that certain sections of the map disappear.
(This is not permanent. Often clicking on the map or zooming again will reset everything) 

**Expected behavior**
When a user is zooming, the full map should load and be visible. 

**Screenshots**

Screen recording here: https://drive.google.com/file/d/1j0J7QRvDwLqMt8j0B8R-dtT1cgGnV20G/view?usp=drivesdk

**Smartphone (please complete the following information):**
 iPhone 7s
Chrome Mobile Browser 

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/631)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by ashwinkjoseph** [comment]
This pretty much looks like the map is just loading slowly.
So when you zoom out, new areas of the map needs to load, this behavior should be observable in Google Maps as well.
It's the same case with Zooming in as well, because when you zoom in, more details needs to be loaded to show more content in the screen.
This is probably due to one of:
- slow network
- slow device
- just random unfortunate timing 😅

**Comment by mcverter** [comment]
@CorporateInvesther @ashwinkjoseph @sabind Can we close this issue?

**Comment by CorporateInvesther** [comment]
Yeah seems like its not being reproduced today! Closing
