### ISSUE TITLE
Implement terms & conditions & privacy policy for web users

### ISSUE THREAD

**Issue by comoser** [reach4help/reach4help#64]
- store the general agreement in localstorage
- speak with `legal` to actually get a `Terms & Conditions` doc ready for the web

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/64)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by s0** [comment]
As important is the Privacy Policy, updated the title to suit.

There was someone on the slack that expressed interest in doing this?

**Comment by ashwinkjoseph** [comment]
@sabind @puzzledbytheweb we are currently storing the timestamp and version for both the `privacy policy` and `terms and conditions`. However, the version is set to be 1 by default for now. 
can we close this now?

**Comment by sabind** [comment]
Yes. When we release new policies we can updated the version in the front end and it will organically track the correct version. The only thing we may want to to before closing this out is to reference and `ENV_VAR` for this `version` so that we don't have to change source code when we release new terms/policies.
