### ISSUE TITLE
Consolidate CONTRIBUTING.md

### ISSUE THREAD

**Issue by mcverter** [reach4help/reach4help#868]
We have two files named Contributing.md

One is in the top-level directory.  One is within web-client/docs.   

These two documents contain much of the same information.  The cardinal rule, though, is "Don't Repeat Yourself"

Decide what information belongs in what document and eliminate repetition.

@schowdhury8 @sabind @puzzledbytheweb  or @ashwinkjoseph would probably be best at making these decisions because they have an overview of the entire project.

--------
### [ZenHub Information](https://app.zenhub.com/workspaces/reach4help-5e8dcbfb14ac087f410cbabb/issues/reach4help/reach4help/868)

*This information is updated automatically. To modify it, please use ZenHub.*

**Comment by mcverter** [comment]
See 
https://github.com/reach4help/reach4help/pull/863

especially this comment:
Since this is a monorepo, I would suggest keeping general contributing guidelines (forking, PRing, etc.) in the top level CONTRIBUTING.md file and keep things specific to a single project (i.e. env vars) in the lower level ones.

**Comment by schowdhury8** [comment]
Since the web-client is the only thing people are really contributing to, seems reasonable to replace our base level [contributing doc](https://github.com/reach4help/reach4help/blob/development/CONTRIBUTING.md) with [the one in web-client](https://github.com/reach4help/reach4help/blob/development/web-client/docs/CodingConventions/CONTRIBUTING.md). @ashwinkjoseph do you have any objections to this?

**Comment by ashwinkjoseph** [comment]
Yea, we can split it up later again if other projects such as map and functions do end up having more activity.
but given that we would soon be joining map project as well into the web-client, we would soon end up only with functions and web-client, so it makes sense right now

**Comment by schowdhury8** [comment]
Done!
